version: '3'

services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio-moderne-81
    ports:
      - "81:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
